/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FrameworkSpanAttributes {
  "langtrace.service.name": string;
  "langtrace.service.type": string;
  "langtrace.service.version"?: string;
  "langtrace.sdk.name": string;
  "langtrace.version": string;
  "langchain.task.name"?: string;
  "langchain.inputs"?: string;
  "langchain.outputs"?: string;
  "langgraph.entrypoint"?: string;
  "langgraph.node"?: string;
  "langgraph.edge"?: string;
  "langgraph.finishpoint"?: string;
  "langgraph.task.name"?: string;
  "llamaindex.task.name"?: string;
  "llamaindex.inputs"?: string;
  "llamaindex.outputs"?: string;
  "langtrace.testId"?: string;
  "dspy.optimizer"?: string;
  "dspy.optimizer.module"?: string;
  "dspy.optimizer.module.prog"?: string;
  "dspy.optimizer.metric"?: string;
  "dspy.optimizer.trainset"?: string;
  "dspy.optimizer.config"?: string;
  "dspy.signature.name"?: string;
  "dspy.signature"?: string;
  "dspy.signature.args"?: string;
  "dspy.signature.result"?: string;
  "dspy.evaluate.devset"?: string;
  "dspy.evaluate.display"?: string;
  "dspy.evaluate.num_threads"?: string;
  "dspy.evaluate.return_outputs"?: string;
  "dspy.evaluate.display_table"?: string;
  "dspy.evaluate.display_progress"?: string;
  "dspy.evaluate.metric"?: string;
  "dspy.evaluate.error_count"?: string;
  "dspy.evaluate.error_lock"?: string;
  "dspy.evaluate.max_errors"?: string;
  "dspy.evaluate.args"?: string;
  "dspy.evaluate.result"?: string;
  "crewai.crew.config"?: string;
  "crewai.agent.config"?: string;
  "crewai.task.config"?: string;
}
