/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FrameworkSpanAttributes {
  "langtrace.service.name": string;
  "langtrace.service.type": string;
  "langtrace.service.version": string;
  "langtrace.sdk.name": "@langtrase/typescript-sdk" | "langtrace-python-sdk";
  "langtrace.version": string;
  "langchain.task.name"?: string;
  "langchain.inputs"?: string;
  "langchain.outputs"?: string;
  "llamaindex.task.name"?: string;
  "llamaindex.inputs"?: string;
  "llamaindex.outputs"?: string;
}
